import json
import re
import logging
from typing import TypeVar, Type, Optional, Union

logger = logging.getLogger(__name__)
T = TypeVar("T", bound=Union[dict, list])


def extract_json(text: str, expected_type: str = "object") -> Optional[Union[dict, list]]:
    """
    Robustly extract JSON from LLM response text.

    Strategy (ordered by priority):
    1. Try direct json.loads (if text is pure JSON)
    2. Try extracting from ```json ... ``` code blocks
    3. Use brace/bracket matching to find the first complete JSON structure
    4. Fallback: use a non-greedy regex as last resort
    """
    def _try_parse(t: str):
        try:
            return json.loads(t)
        except (json.JSONDecodeError, ValueError):
            pass
            
        # Try cleaning trailing commas
        cleaned = re.sub(r',\s*([\]}])', r'\1', t)
        try:
            return json.loads(cleaned)
        except (json.JSONDecodeError, ValueError):
            pass
            
        # Try escaping literal newlines (often generated by LLMs in Vietnamese exams)
        # We only want to escape newlines inside strings, but a simple heuristic 
        # is just replacing literal \n with \\n for the whole string and hoping for the best
        # Actually, Python json.loads allows newlines between tokens, so replacing all
        # newlines is safe EXCEPT it might mess up unescaped \n. A safer approach:
        try:
            # We replace actual newlines with the literal characters '\n'
            # Note: json.loads expects newlines between tokens or inside strings to be \n,
            # but standard JSON requires actual control characters to be escaped.
            cleaned_newlines = cleaned.replace('\n', '\\n')
            return json.loads(cleaned_newlines)
        except (json.JSONDecodeError, ValueError):
            return None

    if not text:
        return None

    text_stripped = text.strip()
    res = _try_parse(text_stripped)
    if res is not None:
        return res

    code_block_pattern = r"```(?:json)?\s*([\s\S]*?)```"
    matches = re.findall(code_block_pattern, text)
    for match in matches:
        res = _try_parse(match.strip())
        if res is not None:
            return res

    opener = "{" if expected_type == "object" else "["
    closer = "}" if expected_type == "object" else "]"

    candidates = _find_balanced_structures(text, opener, closer)
    for candidate in candidates:
        res = _try_parse(candidate)
        if res is not None:
            return res

    pattern = r"\{.*?\}" if expected_type == "object" else r"\[.*?\]"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        res = _try_parse(match.group(0))
        if res is not None:
            return res

    logger.warning(f"JSON extraction failed for text (first 200 chars): {text[:200]}")
    return None


def _find_balanced_structures(text: str, opener: str, closer: str) -> list[str]:
    """Find all balanced brace/bracket structures in text. Returns longest first."""
    candidates = []
    depth = 0
    in_string = False
    escape_next = False
    start_idx = -1

    for i, ch in enumerate(text):
        if escape_next:
            escape_next = False
            continue

        if ch == '\\' and in_string:
            escape_next = True
            continue

        if ch == '"' and not escape_next:
            in_string = not in_string
            continue

        if in_string:
            continue

        if ch == opener:
            if depth == 0:
                start_idx = i
            depth += 1
        elif ch == closer:
            depth -= 1
            if depth == 0 and start_idx >= 0:
                candidates.append(text[start_idx:i + 1])
                start_idx = -1

    candidates.sort(key=len, reverse=True)
    return candidates


def extract_and_validate(text: str, model: Optional[Type[T]] = None, expected_type: str = "object") -> Optional[Union[T, dict, list]]:
    """
    Extract JSON from text and optionally validate against a Pydantic model.
    """
    raw = extract_json(text, expected_type)
    if raw is None:
        return None

    if model is None:
        return raw

    from pydantic import ValidationError
    try:
        return model.model_validate(raw)
    except ValidationError as e:
        logger.warning(f"Pydantic validation failed for {model.__name__}: {e}")
        return None
