"""
Lesson Plan schemas for TOMOSA AI Lesson Planner.

Structured Pydantic models for the lesson plan generation pipeline:
Retriever → Planner → Writer → HITL → Illustrators → Assessment → Formatter.

These schemas replace raw dict fields (lesson_outline: Optional[dict],
assessment_items: Optional[List[dict]]) in LessonPlanState with
validated Pydantic models.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal


# ===== Planner Output =====

class LessonSection(BaseModel):
    """A single section within a lesson plan."""
    section_title: str = Field(description="Section heading (e.g., 'Khởi động')")
    duration_minutes: int = Field(ge=1, le=90, description="Duration in minutes")
    teaching_activities: List[str] = Field(description="Teacher activities for this section")
    student_activities: List[str] = Field(description="Student activities for this section")
    materials_needed: List[str] = Field(default_factory=list, description="Required materials")
    curriculum_standard: Optional[str] = Field(default=None, description="Mapped curriculum standard code")


class LessonOutline(BaseModel):
    """Full lesson outline generated by the Planner node."""
    topic: str = Field(description="Lesson topic title")
    subject: str = Field(description="Subject area")
    grade_level: str = Field(description="Target grade level")
    duration_total: int = Field(ge=1, description="Total lesson duration in minutes")
    learning_objectives: List[str] = Field(description="SMART learning objectives")
    prerequisites: List[str] = Field(default_factory=list, description="Required prior knowledge")
    sections: List[LessonSection] = Field(description="Lesson sections in sequence")
    curriculum_standards_covered: List[str] = Field(default_factory=list)


# ===== Assessment =====

class AssessmentItem(BaseModel):
    """A single assessment question/item."""
    question_type: Literal["multiple_choice", "true_false", "short_answer", "essay", "practical"] = Field(
        description="Type of assessment item"
    )
    question_text: str = Field(description="The question or task")
    bloom_level: Literal["Nhận biết", "Thông hiểu", "Vận dụng", "Vận dụng cao"] = Field(
        description="Bloom's taxonomy level"
    )
    points: float = Field(default=1.0, ge=0.0, description="Point value")
    model_answer: Optional[str] = Field(default=None, description="Expected answer or rubric")
    difficulty: Literal["easy", "medium", "hard"] = Field(default="medium")
    time_estimate_minutes: int = Field(default=5, ge=1, description="Estimated completion time")


class AssessmentSet(BaseModel):
    """Collection of assessment items for a lesson."""
    total_points: float = Field(default=10.0, ge=0.0, description="Total points")
    items: List[AssessmentItem] = Field(description="Assessment items")
    instructions: str = Field(default="", description="General instructions for students")


# ===== Lesson Plan Output =====

class DiagramSpec(BaseModel):
    """Specification for a generated diagram."""
    diagram_type: Literal["mermaid", "matplotlib", "image_gen", "tikz"] = Field(
        description="Type of diagram"
    )
    caption: str = Field(description="Diagram caption")
    generated_code: Optional[str] = Field(default=None, description="Diagram source code")
    image_url: Optional[str] = Field(default=None, description="Rendered image URL")


class LessonPlanOutput(BaseModel):
    """Complete lesson plan output — the final product."""
    topic: str
    subject: str
    grade_level: str
    content_markdown: str = Field(description="Full lesson content in Markdown")
    outline: LessonOutline = Field(description="Lesson structure outline")
    assessment: Optional[AssessmentSet] = Field(default=None, description="Assessment items")
    diagrams: List[DiagramSpec] = Field(default_factory=list, description="Generated diagrams")
    file_url: Optional[str] = Field(default=None, description="Exported file URL (docx/latex)")
    curriculum_standards: List[str] = Field(default_factory=list, description="Matched standards")
    total_tokens_used: int = Field(default=0, ge=0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)
